import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
// import Profile from "/profile.jpg";
import Profile from "./../../public/profile.jpg";

import Whatsapp from "./../../public/whatsapp.svg";
import LinkedIn from "./../../public/linkedin.svg";
import Twitter from "./../../public/twitter.svg";
import Navbar from "./navbar";

const vogue = localFont({
  src: "./fonts/Classyvogueregular.ttf",
  variable: "--font-classy-vogue",
  weight: "100 900",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Peter Mmuo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vogue.variable} antialiased bg-[#f7f7e8]`}
      >
        <header className="w-full fixed top-0 pt-6 px-6 z-[999]">
          <nav className="w-full ">
            <Navbar />
          </nav>
        </header>
        {children}

        <div className="mt-[20vh] max-sm:mt-[100px]  relative  h-[250px] max-sm:h-[150px] text-gray-600 max-450:text-[14px] py-5 w-full">
          <div
            id="footer"
            className="flex flex-row h-full w-full gap-[15%] max-450:gap-[10%] items-start justify-center "
          >
            <div className="flex flex-row gap-2 items-center">
              <div className="overflow-hidden w-5 h-5 rounded-full">
                <Image src={Profile} alt="stars" />
              </div>
              <p>PETER MMUO</p>
            </div>
            <div className="flex flex-row gap-1 ">
              <a
                target="_blank"
                href="https://wa.me/2348131199559"
                className="h-7 w-full max-450:h-6"
              >
                <Image
                  src={Whatsapp}
                  alt="whatsapp"
                  className="w-full h-full "
                />
              </a>

              <a
                target="_blank"
                href="https://x.com/Petermmuo"
                className="h-7 w-full max-450:h-6"
              >
                <Image src={Twitter} alt="twitter" className="w-full h-full" />
              </a>
              <Image
                src={LinkedIn}
                alt="linkedin"
                className="w-full h-7 max-450:h-6"
              />
            </div>
            <div className="flex flex-col gap-2 items-start">
              <p className="mb-2 font-extrabold">CONTACT</p>
              <a
                target="_blank"
                href="mailto:petermmuo05@gmail.com?subject=Hello&body=I%20would%20like%20to%20inquire%20about..."
              >
                Email
              </a>
              <a
                target="_blank"
                href="https://drive.google.com/file/d/17qvTiyJgXcYF4b1hIFkowwtDemuri4D5/view?usp=sharing"
              >
                Resume
              </a>
            </div>
          </div>

          {/* <RetroGrid className="absolute w-full bg-[#55423d] h-full" /> */}
        </div>
      </body>
    </html>
  );
}
